
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Production/Cloud Supabase credentials
const SUPABASE_URL = "https://zwijoxdlxrprtetpvwqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3aWpveGRseHJwcnRldHB2d3F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNjAzODgsImV4cCI6MjA2NDkzNjM4OH0.dbX06EfZPnSnY1VMqghzMDTTttcouQWSCGnekrn5xak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
